name: la_trobada
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.3.0
  mysql1: ^0.20.0
  mysql_client: ^0.0.27
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
